In [36]:
from sklearn import datasets

In [37]:
boston = datasets.load_boston()
X = boston.data
Y = boston.target

In [38]:
X.shape

(506, 13)

In [39]:
import pandas as pd
df = pd.DataFrame(X)
df.columns=boston.feature_names
print()

In [40]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [41]:
for i in range(X.shape[1]):
    new_col_name=boston.feature_names[i]+str('_square')
    df[new_col_name]=df.iloc[:,i]**2
print(df)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  ...  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0  ...
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0  ...
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0  ...
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0  ...
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0  ...
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...  ...
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0  ...
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0  ...
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0  ...
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0  ...
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0  ...

     CHAS_square  NOX_square  RM_square  AGE_square  DIS_square  RAD_square  \
0            0.0    0.289444  43.230625     4251.04   16.728100         1.0
1            0.0    0.219961  41.229241     6225.21   24.672082         4.0
2            0.0    0.219961  51.624225     3733.21   24.672082         4.0
3            0.0    0.209764  48.972004     2097.64   36.750269         9.0
4            0.0    0.209764  51.079609     2937.64   36.750269         9.0
..           ...         ...        ...         ...         ...         ...
501          0.0    0.328329  43.467649     4774.81    6.143458         1.0
502          0.0    0.328329  37.454400     5882.89    5.232656         1.0
503          0.0    0.328329  48.664576     8281.00    4.698056         1.0
504          0.0    0.328329  46.158436     7974.49    5.706843         1.0
505          0.0    0.328329  36.360900     6528.64    6.275025         1.0

     TAX_square  PTRATIO_square     B_square  LSTAT_square
0       87616.0          234.09  157529.6100       24.8004
1       58564.0          316.84  157529.6100       83.5396
2       58564.0          316.84  154315.4089       16.2409
3       49284.0          349.69  155732.8369        8.6436
4       49284.0          349.69  157529.6100       28.4089
..          ...             ...          ...           ...
501     74529.0          441.00  153656.1601       93.5089
502     74529.0          441.00  157529.6100       82.4464
503     74529.0          441.00  157529.6100       31.8096
504     74529.0          441.00  154802.9025       41.9904
505     74529.0          441.00  157529.6100       62.0944

[506 rows x 26 columns]

In [42]:
df.columns[12]

'LSTAT'

In [43]:
df.columns[13]

'CRIM_square'

In [44]:
df.columns[25]

'LSTAT_square'

In [45]:
df.columns[26]

IndexError: index 26 is out of bounds for axis 0 with size 26

In [46]:
for i in range(13,26):
    for j in range(i+1,26):
        new_col_name=df.columns[i]+"--"+df.columns[j]
        df[new_col_name]=df.iloc[:,i]*df.iloc[:,j]

In [47]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,RAD_square--TAX_square,RAD_square--PTRATIO_square,RAD_square--B_square,RAD_square--LSTAT_square,TAX_square--PTRATIO_square,TAX_square--B_square,TAX_square--LSTAT_square,PTRATIO_square--B_square,PTRATIO_square--LSTAT_square,B_square--LSTAT_square
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,87616.0,234.09,1.575296e+05,24.8004,20510029.44,1.380211e+10,2.172912e+06,3.687611e+07,5805.525636,3.906797e+06
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,234256.0,1267.36,6.301184e+05,334.1584,18555417.76,9.225564e+09,4.892413e+06,4.991168e+07,26468.686864,1.315996e+07
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,234256.0,1267.36,6.172616e+05,64.9636,18555417.76,9.037328e+09,9.511321e+05,4.889329e+07,5145.766756,2.506221e+06
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,443556.0,3147.21,1.401596e+06,77.7924,17234121.96,7.675137e+09,4.259912e+05,5.445822e+07,3022.580484,1.346092e+06
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,443556.0,3147.21,1.417766e+06,255.6801,17234121.96,7.763689e+09,1.400104e+06,5.508653e+07,9934.308241,4.475243e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,...,74529.0,441.00,1.536562e+05,93.5089,32867289.00,1.145184e+10,6.969125e+06,6.776237e+07,41237.424900,1.436822e+07
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,...,74529.0,441.00,1.575296e+05,82.4464,32867289.00,1.174052e+10,6.144648e+06,6.947056e+07,36358.862400,1.298775e+07
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,...,74529.0,441.00,1.575296e+05,31.8096,32867289.00,1.174052e+10,2.370738e+06,6.947056e+07,14028.033600,5.010954e+06
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,...,74529.0,441.00,1.548029e+05,41.9904,32867289.00,1.153731e+10,3.129503e+06,6.826808e+07,18517.766400,6.500236e+06
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,...,74529.0,441.00,1.575296e+05,62.0944,32867289.00,1.174052e+10,4.627834e+06,6.947056e+07,27383.630400,9.781707e+06

In [48]:
for i in df.columns:
    print(i)

CRIM
ZN
INDUS
CHAS
NOX
RM
AGE
DIS
RAD
TAX
PTRATIO
B
LSTAT
CRIM_square
ZN_square
INDUS_square
CHAS_square
NOX_square
RM_square
AGE_square
DIS_square
RAD_square
TAX_square
PTRATIO_square
B_square
LSTAT_square
CRIM_square--ZN_square
CRIM_square--INDUS_square
CRIM_square--CHAS_square
CRIM_square--NOX_square
CRIM_square--RM_square
CRIM_square--AGE_square
CRIM_square--DIS_square
CRIM_square--RAD_square
CRIM_square--TAX_square
CRIM_square--PTRATIO_square
CRIM_square--B_square
CRIM_square--LSTAT_square
ZN_square--INDUS_square
ZN_square--CHAS_square
ZN_square--NOX_square
ZN_square--RM_square
ZN_square--AGE_square
ZN_square--DIS_square
ZN_square--RAD_square
ZN_square--TAX_square
ZN_square--PTRATIO_square
ZN_square--B_square
ZN_square--LSTAT_square
INDUS_square--CHAS_square
INDUS_square--NOX_square
INDUS_square--RM_square
INDUS_square--AGE_square
INDUS_square--DIS_square
INDUS_square--RAD_square
INDUS_square--TAX_square
INDUS_square--PTRATIO_square
INDUS_square--B_square
INDUS_square--LSTAT_square
CHAS_square--NOX_square
CHAS_square--RM_square
CHAS_square--AGE_square
CHAS_square--DIS_square
CHAS_square--RAD_square
CHAS_square--TAX_square
CHAS_square--PTRATIO_square
CHAS_square--B_square
CHAS_square--LSTAT_square
NOX_square--RM_square
NOX_square--AGE_square
NOX_square--DIS_square
NOX_square--RAD_square
NOX_square--TAX_square
NOX_square--PTRATIO_square
NOX_square--B_square
NOX_square--LSTAT_square
RM_square--AGE_square
RM_square--DIS_square
RM_square--RAD_square
RM_square--TAX_square
RM_square--PTRATIO_square
RM_square--B_square
RM_square--LSTAT_square
AGE_square--DIS_square
AGE_square--RAD_square
AGE_square--TAX_square
AGE_square--PTRATIO_square
AGE_square--B_square
AGE_square--LSTAT_square
DIS_square--RAD_square
DIS_square--TAX_square
DIS_square--PTRATIO_square
DIS_square--B_square
DIS_square--LSTAT_square
RAD_square--TAX_square
RAD_square--PTRATIO_square
RAD_square--B_square
RAD_square--LSTAT_square
TAX_square--PTRATIO_square
TAX_square--B_square
TAX_square--LSTAT_square
PTRATIO_square--B_square
PTRATIO_square--LSTAT_square
B_square--LSTAT_square

In [49]:
X2=df.values

In [50]:
X2.shape

(506, 104)

In [52]:
X.shape

(506, 13)

In [53]:
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, random_state = 0)
X2_train, X2_test, Y2_train, Y2_test = model_selection.train_test_split(X2, Y, random_state = 0)

In [54]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()
alg2 = LinearRegression()

In [55]:
alg1.fit(X_train, Y_train)
alg2.fit(X2_train, Y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [57]:
Y_pred = alg1.predict(X_test)
train_score = alg1.score(X_train, Y_train)
test_score = alg1.score(X_test, Y_test)
print("Train Score: ", train_score)
print("Test Score: ", test_score)

train2_score = alg2.score(X2_train, Y2_train)
test2_score = alg2.score(X2_test, Y2_test)
print("Train2 Score: ", train2_score)
print("Test2 Score: ", test2_score)

Train Score:  0.7697699488741149
Test Score:  0.6354638433202129
Train2 Score:  0.9420169891451338
Test2 Score:  0.7026180616668884